import { useMemo, useState } from 'react';
import moment from 'moment';
import { Card, CardContent, CardHeader, CardTitle } from '../../components/ui/Card';
import { Badge } from '../../components/ui/Badge';
import { Button } from '../../components/ui/Button';
import { useEmployeeAuth } from '../../context/EmployeeAuthContext';
import { db } from '../../data/db';
import { formatCurrency } from '../../lib/utils';

export function EmployeePayslipsPage() {
  const { employee } = useEmployeeAuth();
  const payslips = useMemo(() => db.payroll.filter((item) => item.employeeId === employee.id).sort((a, b) => b.month.localeCompare(a.month)), [employee.id]);
  const [selectedId, setSelectedId] = useState(payslips[0]?.id || '');
  const payslip = payslips.find((item) => item.id === selectedId) || payslips[0];
  const printPayslip = () => window.print();
  if (!payslip) return <div><h1 className="font-display text-2xl font-bold text-foreground">My payslips</h1><Card className="mt-5"><CardContent className="py-12 text-center text-muted-foreground">No payslips are available yet.</CardContent></Card></div>;
  return <div className="space-y-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="font-display text-2xl font-bold text-foreground">My payslips</h1><p className="mt-1 text-sm text-muted-foreground">View and print your monthly salary statement.</p></div><div className="flex gap-2"><select value={payslip.id} onChange={(event) => setSelectedId(event.target.value)} className="input-base w-auto">{payslips.map((item) => <option key={item.id} value={item.id}>{moment(`${item.month}-01`).format('MMMM YYYY')}</option>)}</select><Button onClick={printPayslip}>Print / Save PDF</Button></div></div><Card className="print:border-0 print:shadow-none"><CardHeader className="border-b border-border"><div className="flex items-start justify-between"><div><p className="text-sm font-medium text-primary">ORCHASP HRMS</p><CardTitle className="mt-1">Salary payslip</CardTitle><p className="mt-1 text-sm text-muted-foreground">{moment(`${payslip.month}-01`).format('MMMM YYYY')}</p></div><Badge variant={payslip.status === 'paid' ? 'success' : payslip.status === 'processed' ? 'primary' : 'warning'} className="capitalize">{payslip.status}</Badge></div></CardHeader><CardContent className="space-y-6 pt-6"><div className="grid gap-4 sm:grid-cols-3"><div><p className="text-xs text-muted-foreground">Employee</p><p className="mt-1 font-medium">{employee.name}</p></div><div><p className="text-xs text-muted-foreground">Employee ID</p><p className="mt-1 font-medium">{employee.employeeId}</p></div><div><p className="text-xs text-muted-foreground">Job title</p><p className="mt-1 font-medium">{employee.jobTitle}</p></div></div><div className="grid gap-5 md:grid-cols-2"><section className="rounded-xl bg-muted/50 p-4"><h2 className="font-medium text-foreground">Earnings</h2><div className="mt-3 space-y-2 text-sm"><div className="flex justify-between"><span>Base salary</span><span>{formatCurrency(payslip.baseSalary)}</span></div><div className="flex justify-between"><span>Bonus</span><span>{formatCurrency(payslip.bonus)}</span></div><div className="flex justify-between border-t border-border pt-2 font-semibold"><span>Gross earnings</span><span>{formatCurrency(payslip.baseSalary + payslip.bonus)}</span></div></div></section><section className="rounded-xl bg-muted/50 p-4"><h2 className="font-medium text-foreground">Deductions</h2><div className="mt-3 space-y-2 text-sm"><div className="flex justify-between"><span>Tax and other deductions</span><span>-{formatCurrency(payslip.deductions)}</span></div><div className="flex justify-between border-t border-border pt-2 font-semibold"><span>Net salary</span><span>{formatCurrency(payslip.netSalary)}</span></div></div></section></div><div className="flex items-center justify-between rounded-xl bg-primary p-5 text-primary-foreground"><span className="font-medium">Net salary payable</span><span className="font-display text-2xl font-bold">{formatCurrency(payslip.netSalary)}</span></div></CardContent></Card></div>;
}
